In [1]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('A_stat_data_112.csv',encoding='utf8')
df2 = df.copy()
df2.head()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072

In [3]:
df2.tail(3)

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
1909956,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-3633088233029289359,703618323232836566
1909957,8,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-3198336096824660439,-371611706378504607
1909958,9,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,8248998181802054321,-371611706378504607

In [4]:
df2.index

RangeIndex(start=0, stop=1909959, step=1)

In [5]:
df2.columns

Index(['grade', 'mission_name', 'mission_difficulty', 'mission_field',
       'mission_type', 'mission_semester_year', 'mission_semester',
       'mission_datetime_utc8', 'mission_status', 'is_completed',
       'completed_at_utc8', 'correct_rate', 'answer_duration_sec',
       'mission_answer_count', 'content_indicator_correct_rate',
       'comprehensive_indicator_correct_rate',
       'explanation_indicator_correct_rate',
       'extraction_indicator_correct_rate', 'form_indicator_correct_rate',
       'first_correct_rate', 'user_id', 'mission_id'],
      dtype='object')

In [6]:
a = df2.columns
a_series = a.to_series()
print(a_series)
a_series.to_csv('work1.csv',index=False)

grade                                                                  grade
mission_name                                                    mission_name
mission_difficulty                                        mission_difficulty
mission_field                                                  mission_field
mission_type                                                    mission_type
mission_semester_year                                  mission_semester_year
mission_semester                                            mission_semester
mission_datetime_utc8                                  mission_datetime_utc8
mission_status                                                mission_status
is_completed                                                    is_completed
completed_at_utc8                                          completed_at_utc8
correct_rate                                                    correct_rate
answer_duration_sec                                      answer_duration_sec
mission_answer_count                                    mission_answer_count
content_indicator_correct_rate                content_indicator_correct_rate
comprehensive_indicator_correct_rate    comprehensive_indicator_correct_rate
explanation_indicator_correct_rate        explanation_indicator_correct_rate
extraction_indicator_correct_rate          extraction_indicator_correct_rate
form_indicator_correct_rate                      form_indicator_correct_rate
first_correct_rate                                        first_correct_rate
user_id                                                              user_id
mission_id                                                        mission_id
dtype: object

In [7]:
b = df2.describe()
print(b)
b.to_excel('work2.xlsx')

              grade  mission_semester_year  is_completed   correct_rate  \
count  1.909959e+06              1909959.0  1.909959e+06  454877.000000
mean   5.949924e+00                  112.0  2.381606e-01       0.412165
std    1.586873e+00                    0.0  4.259580e-01       0.317815
min    4.000000e+00                  112.0  0.000000e+00       0.000000
25%    5.000000e+00                  112.0  0.000000e+00       0.200000
50%    6.000000e+00                  112.0  0.000000e+00       0.400000
75%    7.000000e+00                  112.0  0.000000e+00       0.600000
max    9.000000e+00                  112.0  1.000000e+00       1.000000

       answer_duration_sec  mission_answer_count  \
count        453620.000000          1.909959e+06
mean            147.150187          7.111859e-01
std             328.610611          1.676427e+00
min               1.000000          0.000000e+00
25%              10.000000          0.000000e+00
50%              37.000000          0.000000e+00
75%             176.000000          1.000000e+00
max            3600.000000          2.100000e+02

       content_indicator_correct_rate  comprehensive_indicator_correct_rate  \
count                   106038.000000                         448856.000000
mean                         0.377652                              0.414174
std                          0.475326                              0.401837
min                          0.000000                              0.000000
25%                          0.000000                              0.000000
50%                          0.000000                              0.333333
75%                          1.000000                              0.857143
max                          1.000000                              1.000000

       explanation_indicator_correct_rate  extraction_indicator_correct_rate  \
count                       392142.000000                      414331.000000
mean                             0.385411                           0.438963
std                              0.446032                           0.455068
min                              0.000000                           0.000000
25%                              0.000000                           0.000000
50%                              0.000000                           0.333333
75%                              1.000000                           1.000000
max                              1.000000                           1.000000

       form_indicator_correct_rate  first_correct_rate       user_id  \
count                 78801.000000       473392.000000  1.909959e+06
mean                      0.375179            0.451405 -5.836128e+15
std                       0.482087            0.316127  5.341203e+18
min                       0.000000            0.000000 -9.223321e+18
25%                       0.000000            0.200000 -4.611004e+18
50%                       0.000000            0.400000  6.201597e+16
75%                       1.000000            0.600000  4.565403e+18
max                       1.000000            1.000000  9.218903e+18

         mission_id
count  1.909959e+06
mean  -1.368036e+17
std    5.285432e+18
min   -9.144214e+18
25%   -4.782878e+18
50%   -2.337655e+17
75%    3.909487e+18
max    9.217426e+18

In [8]:
c = df.sort_index(axis=1,ascending=False)
c.head()

,user_id,mission_type,mission_status,mission_semester_year,mission_semester,mission_name,mission_id,mission_field,mission_difficulty,mission_datetime_utc8,...,grade,form_indicator_correct_rate,first_correct_rate,extraction_indicator_correct_rate,explanation_indicator_correct_rate,correct_rate,content_indicator_correct_rate,comprehensive_indicator_correct_rate,completed_at_utc8,answer_duration_sec
0,-8373966078912715601,連續,已派發任務,112,112-2,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,8154604467375388289,文學,易,Mon May 06 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3516683932418412104,連續,已派發任務,112,112-2,05/06 二郎【多元文化教育－傳說故事】（初階）,3762301478342295221,文學,中,Mon May 06 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-65799051578279613,連續,已派發任務,112,112-2,05/09 蚩尤【多元文化教育－傳說故事】（初階）,4652807748946159405,人物,難,Thu May 09 08:00:00 UTC 2024,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-6293485111595748020,非連續,已派發任務,112,112-2,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,240621445882253268,生活知識,中,Mon May 13 08:00:00 UTC 2024,...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4998280410504838977,連續＋圖表,已派發任務,112,112-2,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,-3340858198738005072,自然科學,易,Thu May 16 08:00:00 UTC 2024,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
d = df["mission_name"][0:3]
print(d)
d.to_csv("work3.csv")

0    05/06 虎姑婆【多元文化教育－傳說故事】（初階）
1     05/06 二郎【多元文化教育－傳說故事】（初階）
2     05/09 蚩尤【多元文化教育－傳說故事】（初階）
Name: mission_name, dtype: object

In [10]:
p = 'one two one two one two'.split()
p1 = 'al a2 a3 a4 a5 a6'.split()
df = pd.DataFrame(
  {
    "A": p,
    "B": p1,
    "C": np.random.randn(6),
    "D": np.random.randn(6)
  }
)
df

     A   B         C         D
0  one  al -0.076114  0.622902
1  two  a2 -0.082987  0.062742
2  one  a3  0.356558  0.032512
3  two  a4 -0.493123  0.055718
4  one  a5  1.111147 -0.196134
5  two  a6 -1.066514 -1.596933

In [11]:
df.groupby("A").sum()

          B         C         D
A
one  ala3a5  1.391592  0.459280
two  a2a4a6 -1.642624 -1.478473

In [12]:
df.groupby(["A","B"]).sum()

               C         D
A   B
one a3  0.356558  0.032512
    a5  1.111147 -0.196134
    al -0.076114  0.622902
two a2 -0.082987  0.062742
    a4 -0.493123  0.055718
    a6 -1.066514 -1.596933

In [13]:
stack = df.stack()
stack

0  A         one
   B          al
   C   -0.076114
   D    0.622902
1  A         two
   B          a2
   C   -0.082987
   D    0.062742
2  A         one
   B          a3
   C    0.356558
   D    0.032512
3  A         two
   B          a4
   C   -0.493123
   D    0.055718
4  A         one
   B          a5
   C    1.111147
   D   -0.196134
5  A         two
   B          a6
   C   -1.066514
   D   -1.596933
dtype: object

In [14]:
a = df2.columns
pp2 = []
for j in a:
  try:
    print(df2[j].groupby(df2[j]).count())
    pp2.append(df2[j].groupby(df2[j]).count())
  except:
    print("KeyError")

grade
4    428520
5    438802
6    397674
7    265140
8    204410
9    175413
Name: grade, dtype: int64
mission_name
01/01 我們是用戶還是商品？社群媒體之戰【資訊教育－社群媒體】(中階)     4043
01/01 數據風暴【資訊教育－社群媒體】(中階)                 4043
01/01 表情符號【資訊教育－資訊解讀】(初階)                 7608
01/01 觀影資訊【資訊教育－資訊解讀】(初階)                 7608
01/04 你可能已經犯罪了！【資訊教育－數位倫理】(中階)            4046
                                         ...
5月特別任務－【SDGs 議題】（初階）                      7318
6月特別任務－【SDGs 議題】（中階）                      3711
6月特別任務－【SDGs 議題】（初階）                      7324
9月特別任務－【SDGs 議題】（中階）                     11760
9月特別任務－【SDGs 議題】（初階）                     22647
Name: mission_name, Length: 335, dtype: int64
mission_difficulty
中    1030200
易     487585
難     302401
Name: mission_difficulty, dtype: int64
mission_field
世界櫥窗    198882
人文史地    169453
人物       79521
文化      150953
文學       78925
生活知識    449538
社會科學     98284
自然科學    212554
說明文件     81762
議題      300314
Name: mission_field, dtype: int64
mission_type
連續       1047541
連續＋圖表     227882
非連續       544763
Name: mission_type, dtype: int64
mission_semester_year
112    1909959
Name: mission_semester_year, dtype: int64
mission_semester
112-1    994821
112-2    915138
Name: mission_semester, dtype: int64
mission_datetime_utc8
Fri Dec 22 08:00:00 UTC 2023    11645
Fri Mar 22 08:00:00 UTC 2024    10972
Fri Sep 22 08:00:00 UTC 2023    34407
Mon Apr 01 08:00:00 UTC 2024    21958
Mon Apr 08 08:00:00 UTC 2024    21970
                                ...
Thu Sep 14 08:00:00 UTC 2023    22868
Thu Sep 21 08:00:00 UTC 2023    22902
Thu Sep 28 08:00:00 UTC 2023    23022
Wed May 22 08:00:00 UTC 2024    11016
Wed Nov 22 08:00:00 UTC 2023    11624
Name: mission_datetime_utc8, Length: 86, dtype: int64
mission_status
取消派發        3230
完成任務      453812
已派發任務    1406948
暫停任務       39636
進行任務中       6333
Name: mission_status, dtype: int64
is_completed
0    1455082
1     454877
Name: is_completed, dtype: int64
completed_at_utc8
Fri Apr 05 07:10:18 UTC 2024    1
Fri Apr 05 07:44:10 UTC 2024    1
Fri Apr 05 07:51:52 UTC 2024    1
Fri Apr 05 07:52:32 UTC 2024    1
Fri Apr 05 07:53:22 UTC 2024    1
                               ..
Wed Sep 27 22:50:10 UTC 2023    1
Wed Sep 27 23:01:33 UTC 2023    1
Wed Sep 27 23:06:18 UTC 2023    1
Wed Sep 27 23:11:05 UTC 2023    1
Wed Sep 27 23:20:47 UTC 2023    1
Name: completed_at_utc8, Length: 389446, dtype: int64
correct_rate
0.000000     80825
0.066667      1579
0.133333      2786
0.166667         2
0.200000    107767
0.266667      4079
0.300000         1
0.333333      3120
0.400000     94870
0.466667      1209
0.500000         1
0.533333       733
0.600000     61405
0.666667       327
0.733333       260
0.800000     43527
0.866667       199
0.933333       156
1.000000     52031
Name: correct_rate, dtype: int64
answer_duration_sec
1.0         387
2.0        1067
3.0        4240
4.0       10497
5.0       16398
          ...
3556.0        1
3585.0        1
3598.0        1
3599.0       40
3600.0     2291
Name: answer_duration_sec, Length: 2260, dtype: int64
mission_answer_count
0      1423375
1       105920
2       189753
3        87974
4        41945
        ...
94           1
95           1
113          1
117          1
210          1
Name: mission_answer_count, Length: 69, dtype: int64
content_indicator_correct_rate
0.0    64063
0.5     3859
1.0    38116
Name: content_indicator_correct_rate, dtype: int64
comprehensive_indicator_correct_rate
0.000000    177720
0.111111      1049
0.125000       597
0.142857      1469
0.166667       226
0.200000      1185
0.222222      1296
0.250000      7890
0.285714      1525
0.333333     39670
0.375000       436
0.400000       843
0.428571      1004
0.444444       635
0.500000     70348
0.555556       332
0.571429       488
0.600000       367
0.625000       101
0.666667     25438
0.714286       231
0.750000      3433
0.777778       141
0.800000       123
0.833333        20
0.857143       144
0.875000        40
0.888889       101
1.000000    112004
Name: comprehensive_indicator_correct_rate, dtype: int64
explanation_indicator_correct_rate
0.000000    209054
0.166667      1112
0.200000       194
0.250000       808
0.333333      7409
0.400000       201
0.500000     47586
0.600000       125
0.666667      3904
0.750000       129
0.800000        93
0.833333        54
1.000000    121473
Name: explanation_indicator_correct_rate, dtype: int64
extraction_indicator_correct_rate
0.000000    196367
0.166667       569
0.200000      2839
0.250000      1919
0.333333      7147
0.400000      2080
0.500000     48017
0.600000       947
0.666667      3888
0.750000       451
0.800000       418
0.833333        67
1.000000    149622
Name: extraction_indicator_correct_rate, dtype: int64
form_indicator_correct_rate
0.0    48919
0.5      635
1.0    29247
Name: form_indicator_correct_rate, dtype: int64
first_correct_rate
0.000000     59547
0.066667       970
0.133333      2239
0.200000    115451
0.266667      3689
0.333333      2903
0.400000    103241
0.466667      1156
0.500000         1
0.533333       710
0.600000     67423
0.666667       325
0.700000         1
0.733333       256
0.800000     51153
0.866667       197
0.933333       154
1.000000     63976
Name: first_correct_rate, dtype: int64
user_id
-9223321156357508358    170
-9222609255196723390     86
-9221920182052420668    169
-9221135146560186179    170
-9221071331548492145    170
                       ...
 9212461263078797593    170
 9212946253008955797    170
 9215839480821721378     83
 9216205039327361044    169
 9218903231836064997    169
Name: user_id, Length: 11607, dtype: int64
mission_id
-9144214234931690152    3230
-9108400203314660527    7303
-9027191344670616678    7593
-9015409752689176971    4043
-8952441151237813732    3954
                        ...
 9100905062053433045    7528
 9118852782984091913    7308
 9122207813419383599    3879
 9180294589109158089    7287
 9217425772124953331    7592
Name: mission_id, Length: 339, dtype: int64

In [15]:
with open('次數table_3.txt', 'w', encoding = 'utf-8') as f:
  f.write(str(pp2))
  f.close

In [16]:
df1 = df2.copy()
df1.dropna()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
677,6,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,8.0,2,1.0,0.0,0.0,1.0,1.0,0.6,4524907499274555771,-3755333910581605471
1333,4,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,49.0,4,0.0,0.0,1.0,1.0,0.0,0.4,3879788643829841554,-3755333910581605471
4975,5,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,5.0,2,0.0,1.0,0.0,1.0,0.0,0.4,-3519350230413345858,-3755333910581605471
4976,5,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,15.0,1,1.0,1.0,1.0,1.0,1.0,1.0,8189606819013202011,-3755333910581605471
4977,5,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,3.0,3,0.0,0.0,0.0,0.0,0.0,0.8,-1625213224247900614,-3755333910581605471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1881820,4,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,321.0,2,0.0,1.0,0.0,1.0,0.0,0.4,-6211900089988507564,-3755333910581605471
1881821,4,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,257.0,5,0.0,1.0,0.0,0.0,0.0,0.2,-2754511805693002211,-3755333910581605471
1895973,4,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,21.0,7,0.0,0.0,0.0,1.0,0.0,0.2,3514031899569045869,-3755333910581605471
1896026,6,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,5.0,2,0.0,1.0,1.0,1.0,0.0,0.6,-687516123380719459,-3755333910581605471
1900154,6,11/16 環保吸管【環境教育－環境保護】(初階),中,生活知識,連續,112,112-1,Thu Nov 16 08:00:00 UTC 2023,完成任務,1,...,55.0,6,0.0,0.0,1.0,0.0,0.0,0.2,-5485910994938246922,-3755333910581605471

In [17]:
df1.fillna(5)

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,4998280410504838977,-3340858198738005072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909954,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,5090607127449525741,703618323232836566
1909955,8,04/22 人與鼠的戰爭【環境教育－動物保育】（中階）,易,世界櫥窗,連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,1122720388891184818,8809938774431070893
1909956,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,-3633088233029289359,703618323232836566
1909957,8,4月特別任務－【SDGs 議題】（中階）,5,5,5,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,-3198336096824660439,-371611706378504607
1909958,9,4月特別任務－【SDGs 議題】（中階）,5,5,5,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,5.0,0,5.0,5.0,5.0,5.0,5.0,5.0,8248998181802054321,-371611706378504607

In [19]:
df1.interpolate() # 插值

<ipython-input-19-aa8783c9d0a6>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df1.interpolate() # 插值

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909954,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,5090607127449525741,703618323232836566
1909955,8,04/22 人與鼠的戰爭【環境教育－動物保育】（中階）,易,世界櫥窗,連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,1122720388891184818,8809938774431070893
1909956,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,-3633088233029289359,703618323232836566
1909957,8,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,-3198336096824660439,-371611706378504607
1909958,9,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,8248998181802054321,-371611706378504607

In [29]:
df2 = df.head(10000)

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds,_=default()

gc= gspread.authorize(creds)

gsheets= gc.open_by_url('https://docs.google.com/spreadsheets/d/1znvWvqiHeo_HTHEul0T5zofbKsQSeliGQrrrcIZSeB0/edit?usp=sharing')

from gspread_dataframe import set_with_dataframe
#select new sheets
worksheet = gsheets.get_worksheet(0)
#taking your DataFrameinto Googlesheets
set_with_dataframe(worksheet,df2)